# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and Deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PET_AUCTION }}
        username: ${{ secrets.SSH_KEY }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
    - run: npm run build --if-present
    - run: npm test
